## **NUMPY PROJECT 2 : Employee Data Creation**

##### **Project Objective :** Analyze employee data and answer business questions such as:
##### => Highest paid employee
##### => Lowest paid employee
##### => Average salary
##### => Department-wise analysis
##### => Bonus calculation
##### => Salary hike
##### => Employee filtering
##### => Performance analysis

##### **Step 1:** Import NumPy

In [1]:
import numpy as np

##### **Step 2:** Create Employee Dataset
##### Employee IDs

In [2]:
emp_id = np.array([101,102,103,104,105,106,107,108])

##### Employee Names

In [3]:
emp_name = np.array([
    "Aftab",
    "Rahul",
    "Priya",
    "Sneha",
    "Arjun",
    "Kiran",
    "Neha",
    "Rohan"
])
emp_name

array(['Aftab', 'Rahul', 'Priya', 'Sneha', 'Arjun', 'Kiran', 'Neha',
       'Rohan'], dtype='<U5')

##### Departments

In [4]:
department = np.array([
    "IT",
    "HR",
    "Finance",
    "IT",
    "Sales",
    "HR",
    "Finance",
    "IT"
])
department

array(['IT', 'HR', 'Finance', 'IT', 'Sales', 'HR', 'Finance', 'IT'],
      dtype='<U7')

##### Salary

In [5]:
salary = np.array([
    50000,
    45000,
    70000,
    55000,
    40000,
    48000,
    75000,
    60000
])
salary

array([50000, 45000, 70000, 55000, 40000, 48000, 75000, 60000])

##### Experience

In [6]:
experience = np.array([
    2,
    1,
    5,
    3,
    1,
    2,
    6,
    4
])
experience

array([2, 1, 5, 3, 1, 2, 6, 4])

##### Performance Rating

In [7]:
rating = np.array([
    4,
    3,
    5,
    4,
    2,
    3,
    5,
    4
])
rating

array([4, 3, 5, 4, 2, 3, 5, 4])

##### **Step 3:** Display Complete Employee Data

In [8]:
for i in range(len(emp_id)):
    print(emp_id[i],
          emp_name[i],
          department[i],
          salary[i],
          experience[i],
          rating[i])

101 Aftab IT 50000 2 4
102 Rahul HR 45000 1 3
103 Priya Finance 70000 5 5
104 Sneha IT 55000 3 4
105 Arjun Sales 40000 1 2
106 Kiran HR 48000 2 3
107 Neha Finance 75000 6 5
108 Rohan IT 60000 4 4


##### **Step 4:** Total Number of Employees

In [9]:
print(len(emp_id))

8


##### **Step 5:** Average Salary

In [10]:
print(np.mean(salary))

55375.0


##### **Step 6:** Highest Salary

In [11]:
max_salary = np.max(salary)
print(max_salary)

75000


##### **Step 7:** Employee with Highest Salary

In [12]:
index = np.argmax(salary)
print(emp_name[index])
print(salary[index])

Neha
75000


##### **Step 8:** Lowest Salary Employee

In [13]:
index = np.argmin(salary)
print(emp_name[index])
print(salary[index])

Arjun
40000


##### **Step 9:** Employees Earning More Than 50,000

In [14]:
print(emp_name[salary > 50000])

['Priya' 'Sneha' 'Neha' 'Rohan']


##### **Step 10:** Employees in IT Department

In [15]:
print(emp_name[department == "IT"])

['Aftab' 'Sneha' 'Rohan']


##### **Step 11:** Employees Having Experience More Than 3 Years

In [16]:
print(emp_name[experience > 3])

['Priya' 'Neha' 'Rohan']


##### **Step 12:** Add 10% Salary Hike

In [17]:
new_salary = salary * 1.10
print(new_salary)

[55000. 49500. 77000. 60500. 44000. 52800. 82500. 66000.]


##### **Step 13:** Bonus Based on Performance
##### Rating 5 → ₹10000 Bonus
##### Rating 4 → ₹5000 Bonus
##### Others → ₹2000 Bonus

In [18]:
bonus = np.where(
    rating == 5,
    10000,
    np.where(
        rating == 4,
        5000,
        2000
    )
)
print(bonus)

[ 5000  2000 10000  5000  2000  2000 10000  5000]


##### **Step 14:** Final Salary

In [19]:
final_salary = salary + bonus
print(final_salary)

[55000 47000 80000 60000 42000 50000 85000 65000]


##### **Step 15:** Top Performers

In [21]:
print(emp_name[rating == 5])

['Priya' 'Neha']


##### **Step 16:** Employees Eligible for Promotion
##### Conditions:
##### Experience ≥ 3
##### Rating ≥ 4

In [22]:
promotion = emp_name[ (experience >= 3) & (rating >= 4)]
print(promotion)

['Priya' 'Sneha' 'Neha' 'Rohan']


##### **Step 17:** Department-wise Employee Count

In [23]:
unique_dept = np.unique(department)
for dept in unique_dept:
    count = np.sum(department == dept)
    print(dept, count)

Finance 2
HR 2
IT 3
Sales 1


##### **Step 18:** Department-wise Average Salary

In [24]:
for dept in np.unique(department):
    avg_salary = np.mean(
        salary[department == dept]
    )
    print(dept, avg_salary)

Finance 72500.0
HR 46500.0
IT 55000.0
Sales 40000.0


##### **Step 19:** Sort Employees by Salary
##### Ascending

In [25]:
index = np.argsort(salary)
print(emp_name[index])

['Arjun' 'Rahul' 'Kiran' 'Aftab' 'Sneha' 'Rohan' 'Priya' 'Neha']


##### Descending

In [26]:
index = np.argsort(salary)[::-1]
print(emp_name[index])

['Neha' 'Priya' 'Rohan' 'Sneha' 'Aftab' 'Kiran' 'Rahul' 'Arjun']


##### **Step 20:** Statistical Analysis

In [27]:
print(np.mean(salary))
print(np.median(salary))
print(np.std(salary))
print(np.var(salary))

55375.0
52500.0
11444.840540610428
130984375.0


##### **Step 21:** Employee Search by ID

In [28]:
search_id = 104
index = np.where(emp_id == search_id)
print(emp_name[index])

['Sneha']


##### **Step 22:** Generate Employee Report

In [29]:
for i in range(len(emp_id)):
    print(
        f"""
Employee ID : {emp_id[i]}
Employee Name : {emp_name[i]}
Department : {department[i]}
Salary : {salary[i]}
Experience : {experience[i]}
Rating : {rating[i]}
Bonus : {bonus[i]}
Final Salary : {final_salary[i]}
----------------------------------
"""
    )


Employee ID : 101
Employee Name : Aftab
Department : IT
Salary : 50000
Experience : 2
Rating : 4
Bonus : 5000
Final Salary : 55000
----------------------------------


Employee ID : 102
Employee Name : Rahul
Department : HR
Salary : 45000
Experience : 1
Rating : 3
Bonus : 2000
Final Salary : 47000
----------------------------------


Employee ID : 103
Employee Name : Priya
Department : Finance
Salary : 70000
Experience : 5
Rating : 5
Bonus : 10000
Final Salary : 80000
----------------------------------


Employee ID : 104
Employee Name : Sneha
Department : IT
Salary : 55000
Experience : 3
Rating : 4
Bonus : 5000
Final Salary : 60000
----------------------------------


Employee ID : 105
Employee Name : Arjun
Department : Sales
Salary : 40000
Experience : 1
Rating : 2
Bonus : 2000
Final Salary : 42000
----------------------------------


Employee ID : 106
Employee Name : Kiran
Department : HR
Salary : 48000
Experience : 2
Rating : 3
Bonus : 2000
Final Salary : 50000
-------------------

##### Q1. Who is the highest paid employee?

In [30]:
emp_name[np.argmax(salary)]

np.str_('Neha')

##### Q2. How many employees earn above average salary?

In [31]:
np.sum(salary > np.mean(salary))

np.int64(3)

##### Q3. Which department has highest average salary?

In [32]:
unique_dept = np.unique(department)
avg_salaries = [
    np.mean(salary[department == dept])
    for dept in unique_dept
]
print(unique_dept[np.argmax(avg_salaries)])

Finance


##### Q4. Find employees eligible for promotion.

In [33]:
emp_name[(experience>=3) & (rating>=4)]

array(['Priya', 'Sneha', 'Neha', 'Rohan'], dtype='<U5')

##### Q5. Calculate total salary expenditure.

In [34]:
np.sum(salary)

np.int64(443000)