## **NUMPY PROJECT 1 : Students Data Creation**

##### **NumPy Mini Project: Student Performance Analysis System**
##### **This project covers:**
##### => Creating data using NumPy
##### => Performing NumPy operations
##### => Solving real-world questions
##### => Statistical analysis
##### => Filtering
##### => Sorting
##### => Indexing
##### => Aggregation

##### **Step 1 :** Import Library 

In [1]:
import numpy as np

##### **Step 2 :** Create Dataset
##### Example : Suppose we have marks of 5 students in 4 subjects.Rows = Students, Columns = Subjects

In [2]:
students = np.array([
    [85, 78, 92, 88],
    [76, 81, 79, 85],
    [90, 95, 93, 97],
    [65, 70, 68, 72],
    [88, 84, 91, 89]
])

In [3]:
students

array([[85, 78, 92, 88],
       [76, 81, 79, 85],
       [90, 95, 93, 97],
       [65, 70, 68, 72],
       [88, 84, 91, 89]])

In [4]:
print(students)

[[85 78 92 88]
 [76 81 79 85]
 [90 95 93 97]
 [65 70 68 72]
 [88 84 91 89]]


##### **Step 3 :** Check Dataset Information

In [5]:
print(students.shape)

(5, 4)


##### Total 5 Students, 4 Subjects

In [6]:
print(students.ndim)

2


In [7]:
print(students.size)

20


In [10]:
print(students.dtype)

int64


##### **Step 4 :** Calculate Total Marks
##### Student Wise Total

In [11]:
total_marks = np.sum(students, axis=1)
print(total_marks)

[343 321 375 275 352]


##### **Step 5 :** Calculate Average Marks

In [12]:
average_marks = np.mean(students, axis=1)
print(average_marks)

[85.75 80.25 93.75 68.75 88.  ]


##### **Step 6 :** Find Highest Marks

In [13]:
highest = np.max(students)
print(highest)

97


##### **Step 7 :** Find Lowest Marks

In [14]:
lowest = np.min(students)
print(lowest)

65


##### **Step 8 :** Subject Wise Average

In [15]:
subject_avg = np.mean(students, axis=0)
print(subject_avg)

[80.8 81.6 84.6 86.2]


##### **Step 9 :** Find Topper

In [16]:
topper_index = np.argmax(total_marks)
print(topper_index)

2


##### **Step 10 :** Find Weakest Student

In [17]:
weak_student = np.argmin(total_marks)
print(weak_student)

3


##### **Step 11 :** Students Scoring Above 85 Average

In [18]:
average_marks = np.mean(students, axis=1)
result = average_marks > 85
print(result)

[ True False  True False  True]


##### Display Those Students

In [19]:
print(students[average_marks > 85])

[[85 78 92 88]
 [90 95 93 97]
 [88 84 91 89]]


##### **Step 12 :** Add Bonus Marks
##### Add 5 marks to every subject.

In [20]:
bonus = students + 5
print(bonus)

[[ 90  83  97  93]
 [ 81  86  84  90]
 [ 95 100  98 102]
 [ 70  75  73  77]
 [ 93  89  96  94]]


##### **Step 13 :** Grade Assignment

In [21]:
average_marks = np.mean(students, axis=1)
grades = np.where(
    average_marks >= 90, 'A',
    np.where(
        average_marks >= 80, 'B',
        np.where(
            average_marks >= 70, 'C', 'D'
        )
    )
)
print(grades)

['B' 'B' 'A' 'D' 'B']


##### **Step 14 :** Sort Students by Total Marks

In [22]:
sorted_students = np.argsort(total_marks)
print(sorted_students)

[3 1 0 4 2]


##### Descending Order

In [23]:
print(np.argsort(total_marks)[::-1])

[2 4 0 1 3]


##### **Step 15 :** Standard Deviation

In [24]:
std = np.std(students)
print(std)

9.11098238391448


##### **Step 16 :** Variance

In [25]:
var = np.var(students)
print(var)

83.01


##### **Step 17 :** Median

In [26]:
median = np.median(students)
print(median)

85.0


##### **Step 18 :** Reshape Data

In [27]:
arr = np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


##### **Step 19 :** Matrix Operations
##### Create Matrices

In [29]:
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

##### Addition

In [30]:
print(A+B)

[[ 6  8]
 [10 12]]


##### Subtraction

In [31]:
print(A-B)

[[-4 -4]
 [-4 -4]]


##### Multiplication

In [32]:
print(A*B)

[[ 5 12]
 [21 32]]


##### Dot Product

In [33]:
print(np.dot(A,B))

[[19 22]
 [43 50]]


##### **Step 20 :** Real Interview Questions
##### Q1. Find Students Scoring More Than 90

In [34]:
print(students[students > 90])

[92 95 93 97 91]


##### Q2. Count Students

In [35]:
print(len(students))

5


##### Q3. Count Subjects

In [36]:
print(students.shape[1])

4


##### Q4. Percentage Calculation

In [37]:
percentage = total_marks/400*100
print(percentage)

[85.75 80.25 93.75 68.75 88.  ]


##### Q5. Pass or Fail
##### Passing Marks = 40

In [38]:
result = np.all(students >= 40, axis=1)
print(result)

[ True  True  True  True  True]
